StringLiterals:
  Enabled: false

SignalException:
  Enabled: false

AlignParameters:
  Enabled: false

MultilineTernaryOperator:
  Enabled: false

LineLength:
  Enabled: false

RedundantSelf:
  Enabled: false

GuardClause:
  Enabled: false

Next:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  Enabled: false

