language: ruby
gemfile: Gemfile.ci
install: bundle install -j4 --path vendor/bundle
cache:
  directories:
    - vendor/bundle
rvm:
  - 1.9.2
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
